template = ["The climate is so weird. witnessed [unusual_weather] in chennai today",
"I met a survivor from [tn_place]. They claimed they found a huge supply of [rare_stuff]",
"passed through [chennai_area]. [place_desc]",
"I met a scavenger today who told me he belonged to a cult that [cults_doing_things]",
"Witnessed a fight between [cult_] and [cult2]",
"Last night made it to [chennai_landmark]. It was occupied by some people. They were kind",
"Met a survivor who claimed he was a member of [cult_]. He promised [nostalgic_thing] if I find him [rare_stuff]",
"I was singing [tamil_song] the whole day. Heart is filled with [memories_]",
"[chennai_landmark] was covered in [post_apoc_waste]. Joined with [cult_] to clean it",
"remembering a time when [tn_place] was great town and not just a place full of [post_apoc_waste]",
"Met a scavenger in [chennai_area] who said he was craving [food_]",
"Next time I met a person I am going to ask them where can I find [rare_stuff]",
"Travelled to [chennai_landmark]. [place_desc]. The place is filled with [memories_]",
"Met a [gender_]. They [cults_doing_things]",
"There was [unusual_weather] today. Took shelter in [chennai_landmark]",
"Found a [nostalgic_thing] at the dumpyard in [chennai_area]. Those were simpler times",
"Could smell someone cooking [food_] inside [chennai_landmark]. [ques_engaging]",
"Next time I met a person I am going to ask them to join me to [cults_doing_things]",
"Found a [vehicle_] with full tank. Took it for a spin at [chennai_area]",
"Remembered this movie - [post_apoc_movie]. Imagine thinking post apocalypse would be anything like that lmao",
"Remembered about this movie - [tamil_movie]. [movie_desc]",
"[cult_] and [cult2] are having a huge party. I can hear them playing [tamil_dance_number]. [ques_engaging]",
"Danced to [tamil_dance_number] like no one's watching. Hmm actually no one was, there was not a single soul in [chennai_landmark]",
"Found a [music_instrument]. Played [tamil_song] all day",
"Scavenged [chennai_area] with a [gender_] from [country_]. Found a huge stash of [rare_stuff]",
"Found a [music_instrument]. Played songs from [tamil_movie] all day",
"Met a [gender_] at [chennai_landmark]. They [weird_body_parts]",
"Met an amazingly beautiful lady. I am sure she is from [tn_place]",
"[chennai_area] was a mess of [post_apoc_waste]. looks absolutelty terrible",
"As [unusual_weather] settled in at [chennai_area]. I sang [tamil_song]",
"Someone has painted and redecorated [chennai_landmark]. looks [place_desc]",
"Cooking [food_]. Hope it doesn't attract any [violent_being]",
"Met a [gender_] who promised me [rare_stuff] if I find them [nostalgic_thing]",
"Went to a farmers market, they were selling [post_apoc_harvest]",
"cooked [food_]",
"Met a youngling who claimed the only song he knew was [tamil_song]",
"Take care of your mental health kids. Trust me when I say the world is not kind at all",
"Scavenged [chennai_area] with a [gender_] from [country_]. Found a huge stash of [nostalgic_thing]",
"I could hear [tamil_song] in the [chennai_landmark]. looks like there are bunch of people. [ques_engaging]",
"Met a [tn_place] [gender_] who warned me about a possible war between [cult_] and [cult2]",
"I feel like wearing [dress_] today",
"A survivor warned me not to go to [chennai_landmark] as it is full of [violent_being]. But I am, wish me luck",
"My search for [rare_stuff] was intruded by a [violent_being]. Bleeding everywhere, wish me health",
"I miss the times when [current_things]",
"Scavenged [chennai_area] with a [gender_]. Found a huge stash of [alcohol_]. We drank and discussed about the times when [current_things]",
"Looked for [nostalgic_thing] in many places. Nowhere to be found",
"Encountered [violent_being] at [chennai_landmark]. Barely escaped",
"I almost beat a [country_p] survivor to death over a fight for [rare_stuff]",
"Fought a bunch of [violent_being] with [cult_]. We split the spoils later",
"Met a scavenger who promised me [nostalgic_thing] if I cook them [food_]",
"Met a group beatiful women who claimed to be from [tn_place]. We drank and danced to [tamil_dance_number]",
"Hearing [tamil_dance_number] from [chennai_landmark]. I am sure it is occupied by [cult_]",
"I wonder if there are any survivors in [country_]",
"[tamil_proverb]. No wonder the world ended",
"A crazy survivor warned me not to eat [food_] as they beleived it will turn us into [violent_being] ",
"Witnessed a [country_p] killing a member of the cult, [cult_]. Hope it doesnt start a war",
"Met a survivor from [tn_place]. They said they walked all the way from there.",
"Met a survivor from [tn_place]. They said the whole place is now infested with [violent_being] and [post_apoc_waste]",
"Cooked a new dish with [post_apoc_harvest]",
"What do you think survivors in [country_] would be doing right now",
"Met a youngling who claimed the only song he knew was [tamil_song]",
"Met a [tn_place] survivor who [weird_body_parts]",
"Drank [alcohol_] with a [gender_] who [weird_body_parts]",
"Found a [weapon_]. Hope this will guard me from [violent_being]",
"Found a [weapon_]. Hope this will guard me from [cult_]",
"Met a survivor from [tn_place]. They said promised me [weapon_] if I find them [nostalgic_thing]",
"I always wanted to go to [tn_place]. Someday",
"If I survive this year, I will [dreams_]",
"Met a bunch of kids who think [cult_] is crazy. Lol, Only if they had lived in a time when [current_things]",
"Made a campfire at [chennai_landmark] and it attracted [violent_being]. Escaped with few scratches. How dumb can I be?",
"Remebering a time when [current_things]. No wonder the world ended",
"What do you think survivors in [tn_place] would be doing right now",
"Sometimes, at nights, I dream of  [actress_]",
"Good news for once, I found a whole bunch of [rare_stuff]",
"Thinking about Good ol times when we watched [tamil_movie] on TV",
"We have a saying in [tn_place] told a survivor, [tamil_proverb]",
"Good news for once, I found a whole case of [alcohol_]",
"Assaulted a [tn_place] survivor with [weapon_] after they tried to steal my food",
"[tamil_proverb]. Have to teach this to kids today",
"Met a couple who claimed they [cults_doing_things]",
"Found a full bottle of [alcohol_] yesterday. When I woke up, I found myself in [chennai_landmark]",
"took a shelter from [unusual_weather]. remembered the simpler times",
"A bunch of men from [tn_place] were fighting for a newspaper clipping of [actress_]",
"As I passed through [chennai_landmark] mind was filled with [memories_]",
"Made a campfire at [chennai_landmark] and drank [alcohol_] with [cult_]",
"I wonder if there are any survivors in [tn_place]",
"Sometimes I am jealous of these kids, they dont know a world when [current_things]",
"Found a vantage point at [chennai_landmark]. I saw [cult_] who [cults_doing_things]",
"Took shelter from [unusual_weather] along with [cult_]. They claimed they [cults_doing_things]",
"Finished my last supply of [post_apoc_harvest]",
"Finished my last supply of [food_]",
"A huge war broke out between cults because [cult_] claimed [actress_] is the most beatiful of all time",
"A bunch of men from [country_] were fighting for a newspaper clipping of [actress_]",
"Made my way from [chennai_area] to [chennai_landmark]. Craving [food_]",
"Encountered a cult- [cult_] who [cults_doing_things]. I thought times were crazy when [current_things] a long time ago.",
"If I survive this year, I will [dreams_]",
"One day, I will [dreams_]",
"Met a group of survivors. I told them I am going to [dreams_]. They were interested",
"Assaulted a [country_p] scavenger with [weapon_] after they tried to steal my food",
"Snuck into [chennai_landmark]. It was full of [violent_being]. Found [nostalgic_thing]",
"[chennai_landmark] was complete mess. looks nasty",
"Met a ugly looking man who [weird_body_parts]. If i had a [weapon_]. I would have put him out of his misery",
"Met a friendly [violent_being]. Is the world returning to normal ?",
"Remembered watching [tamil_movie] in theatre. Those were the times",
"Encountered a scavenger who was playing [tamil_song] on [music_instrument] in garbage pile at [chennai_landmark]",
"Found [weapon_]. Going to show [cult_] their place",
"There is a rumour about a new fringe group that [cults_doing_things]",
"A survivor told me [tamil_movie] is the best movie of all time. We deserved the apocalypse",
"Met a [gender_] from [tn_place] who exchanged with me [nostalgic_thing] for a dvd copy of [tamil_movie]",
"Met a couple outside [chennai_landmark]. crazy people",
"Encoured a cult that seek something called The Holy grail and beleive it is [nostalgic_thing]",
"Met a couple in [chennai_landmark]. They were getting engaged",
"One day I am gonna build a ship and travel to [country_]",
"A [country_p] [gender_] joined [cult_]",
"Met a survivor from [tn_place] who claimed he knew me from twitter",
"Met an old scavenger who told me he had no memory of when [current_things]",
"Made a campfire at [chennai_landmark] and danced to [tamil_dance_number] with [country_p] women",
]